name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: 设置 .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    - name: 构建
      run: dotnet build --no-restore
      working-directory: Push_test
    - name: 执行
      run: dotnet run --no-build
      working-directory: Push_test