name: CI

on:
  push:
    tags:
      - '*'
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: 设置 .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: 构建
      run: dotnet publish -c Release -o ./publish
      working-directory: Push_test

    - name: 执行
      run: ./publish/Push_test
      working-directory: Push_test

    - name: 上传可执行文件到 Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: Push_test/publish/Push_test
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}